name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

jobs:
  BuildAndTest:

    runs-on: [self-hosted, Linux]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --collect:"XPlat Code Coverage" --logger trx --verbosity normal
    - name: Test Report    
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Dotnet Tests 
        path: TestResults/**/*.trx
        path-replace-backslashes: 'false'
        reporter: 'dotnet-trx'
        only-summary: 'false'
        list-suites: 'all'
        list-tests: 'all'
        max-annotations: '10'
        fail-on-error: 'true'
